ARG BUILD_FROM
FROM $BUILD_FROM

ENV LANG C.UTF-8
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apk add --no-cache git npm

COPY . /
RUN chmod a+x /run.sh
RUN chmod a+x /finish.sh

#RUN cd /Baileys && npm install -force && cd ../ && npm install -force

EXPOSE 3000
CMD [ "/run.sh" ]